name: RC Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, development ]

jobs:
  package_build_test:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build RC
      run: swift build -v
    - name: Tests
      run: swift test
